### ISSUE TITLE
Reporte TextBox

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-CxrlosMX#2]
[Reporte_TextBox_personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-CxrlosMX/files/6330571/Reporte_TextBox_personalizado.pdf)

**Comment by MLR062998** [comment]
20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
